### ISSUE TITLE
[ui, feat] 세미나2 필수과제

### ISSUE THREAD

**Issue by murjune** [IN-SOPT-ANDROID/JunWon#2]
## ISSUE
- 세미나2 필수과제

## To-Do
- [x] recycler뷰 item ui 만들기
- [x] 바텀 네비 연동
- [x] 바텀네비 Scroll To Top 기능 추가
- [x] 리사이클러뷰 Header까지 스크롤
- [ ] SharedPreference Gson으로 직렬화한 로직 Parcelable or Serializable로 바꾸기
